services:
  db:
    image: postgres:9.6
    volumes:
    - dados:/var/lib/postgres/data
    - ./scripts:/scripts
    - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql123
  frontend:
    image: nginx:1.13
    volumes:
    - ./web:/usr/share/nginx/html/
    ports:
    - 80:80
volumes:
  dados:
